"""
Server Angel Email Reporter Module
Builds email content for health reports and deployment notifications.
"""

from datetime import datetime
import socket
from config import Config


class EmailReporter:
    """Handles email report generation."""

    @staticmethod
    def build_health_report(health_data, report_type="daily"):
        """Build health check email report."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        hostname = socket.gethostname()

        subject = f"🛡️ Server Angel - {report_type.title()} Health Report - {hostname}"

        body = f"""
🛡️ SERVER ANGEL - {report_type.upper()} HEALTH REPORT
{'=' * 50}

Server: {hostname}
Report Time: {timestamp}
Report Type: {report_type.title()}

🖥️  SYSTEM STATUS
{'-' * 20}

"""

        # System information
        system = health_data.get('system', {})
        if 'error' in system:
            body += f"❌ System Check Failed: {system['error']}\n\n"
        else:
            body += f"CPU Usage: {system.get('cpu_usage', 'N/A')}\n"
            body += f"Memory Usage: {system.get('memory_usage', 'N/A')}\n"
            body += f"Disk Usage: {system.get('disk_usage', 'N/A')}\n"
            body += f"Server Uptime: {system.get('uptime', 'N/A')}\n\n"

        # Services information
        body += f"🔧 SERVICES STATUS\n{'-' * 20}\n\n"

        services = health_data.get('services', [])
        all_services_ok = True
        running_count = 0
        total_count = len([s for s in services if not s.get('status') == 'NOT_CONFIGURED'])

        for service in services:
            name = service.get('name', 'Unknown')
            status = service.get('status', 'UNKNOWN')
            details = service.get('details', '')

            # Skip not configured services in the list
            if status == 'NOT_CONFIGURED':
                continue

            if status in ['RUNNING', 'OK']:
                emoji = "✅"
                running_count += 1
            elif status in ['STOPPED', 'FAILED', 'ERROR']:
                emoji = "❌"
                all_services_ok = False
            else:
                emoji = "⚠️"

            body += f"{emoji} {name}: {status}"
            if details and status != 'RUNNING':
                body += f" ({details})"
            body += "\n"

        # Summary
        body += f"\n📊 SUMMARY\n{'-' * 10}\n"

        if all_services_ok and 'error' not in system:
            body += f"✅ All systems operational ({running_count}/{total_count} services running)\n"
        else:
            body += f"⚠️  Issues detected - {running_count}/{total_count} services running\n"

        body += f"\nNext report: {Config.EVENING_REPORT if report_type == 'morning' else Config.MORNING_REPORT} (server time)"
        body += f"\n\n{'=' * 50}"
        body += "\n\n🤖 Generated by Server Angel v2.0"
        body += f"\nServer: {hostname}"
        body += "\n\n👨‍💻 Developed by Kassim Muhammad Atiku"
        body += "\n📧 GitHub: https://github.com/diamond-kassim-3"
        body += "\n🏢 NHT Corporations Limited"
        body += "\n\n📄 Licensed under MIT License"
        body += "\n   Copyright © 2025 NHT Corporations Limited"

        return subject, body

    @staticmethod
    def build_deployment_report(deployment_data):
        """Build deployment notification email report."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        hostname = socket.gethostname()

        # Determine if deployment was successful
        success = deployment_data.get('success', False)
        commit_hash = deployment_data.get('commit_hash', 'Unknown')

        if success:
            subject = f"🚀 Server Angel - Deployment Successful - {commit_hash[:8]} - {hostname}"
            emoji = "✅"
        else:
            subject = f"❌ Server Angel - Deployment Failed - {commit_hash[:8] if commit_hash != 'Unknown' else 'Unknown'} - {hostname}"
            emoji = "❌"

        body = f"""
🚀 SERVER ANGEL - DEPLOYMENT REPORT
{'=' * 40}

Server: {hostname}
Report Time: {timestamp}
Commit: {commit_hash}
Status: {'SUCCESS' if success else 'FAILED'}

📋 DEPLOYMENT DETAILS
{'-' * 22}

"""

        # Deployment steps
        steps = deployment_data.get('steps', [])
        if steps:
            body += "Deployment Steps:\n"
            for step in steps:
                step_name = step.get('step', 'Unknown').replace('_', ' ').title()
                step_status = step.get('status', 'unknown').upper()
                step_emoji = "✅" if step_status == 'SUCCESS' else "❌" if step_status == 'FAILED' else "⏳"
                body += f"  {step_emoji} {step_name}: {step_status}\n"

                if step.get('error'):
                    body += f"     Error: {step['error']}\n"
            body += "\n"

        # Dependencies
        if deployment_data.get('requirements_changed'):
            body += "Dependencies Updated: Yes\n"
        else:
            body += "Dependencies Updated: No (requirements.txt unchanged)\n"

        # Services restarted
        restart_details = None
        for step in steps:
            if step.get('step') == 'restart_services' and step.get('details'):
                restart_details = step['details']
                break

        if restart_details:
            results = restart_details.get('results', [])
            if results:
                body += f"\nServices Restarted:\n"
                for result in results:
                    svc_name = result.get('name', 'Unknown')
                    svc_result = result.get('result', {})
                    svc_success = svc_result.get('success', False)
                    svc_emoji = "✅" if svc_success else "❌"
                    body += f"  {svc_emoji} {svc_name}\n"

        # Errors
        if 'error' in deployment_data:
            body += f"\n❌ ERROR DETAILS\n{'-' * 15}\n"
            body += f"{deployment_data['error']}\n"

        # Success message
        if success:
            body += f"\n{emoji} Deployment completed successfully!\n"
            body += "All services have been updated and restarted.\n"
        else:
            body += f"\n{emoji} Deployment failed!\n"
            body += "Please check the errors above and review server logs.\n"

        body += f"\n\n{'=' * 40}"
        body += "\n\n🤖 Generated by Server Angel v2.0"
        body += f"\nServer: {hostname}"
        body += "\n\n👨‍💻 Developed by Kassim Muhammad Atiku"
        body += "\n📧 GitHub: https://github.com/diamond-kassim-3"
        body += "\n🏢 NHT Corporations Limited"
        body += "\n\n📄 Licensed under MIT License"
        body += "\n   Copyright © 2025 NHT Corporations Limited"

        return subject, body

    @staticmethod
    def build_error_report(error_message, context="general"):
        """Build error notification email."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        hostname = socket.gethostname()

        subject = f"🚨 Server Angel - Error Alert - {context.title()} - {hostname}"

        body = f"""
🚨 SERVER ANGEL - ERROR ALERT
{'=' * 30}

Server: {hostname}
Report Time: {timestamp}
Context: {context.title()}

❌ ERROR DETAILS
{'-' * 15}

{error_message}

🔧 ACTION REQUIRED
{'-' * 18}

Please check the server logs and resolve the issue.

{'=' * 30}

🤖 Generated by Server Angel v2.0
Server: {hostname}

👨‍💻 Developed by Kassim Muhammad Atiku
📧 GitHub: https://github.com/diamond-kassim-3
🏢 NHT Corporations Limited

📄 Licensed under MIT License
   Copyright © 2025 NHT Corporations Limited
"""

        return subject, body
