"""
Server Angel Email Reporter Module
Builds email content for health reports and deployment notifications.
"""

from datetime import datetime
import socket
from config import Config


class EmailReporter:
    """Handles email report generation with HTML support."""

    # ==========================
    # HTML TEMPLATES
    # ==========================
    HTML_TEMPLATE = """
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; background-color: #f4f6f9; margin: 0; padding: 0; }}
            .container {{ max-width: 600px; margin: 20px auto; background: #fff; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); overflow: hidden; }}
            .header {{ background: #2c3e50; color: #fff; padding: 20px; text-align: center; }}
            .header h1 {{ margin: 0; font-size: 22px; }}
            .header p {{ margin: 5px 0 0; opacity: 0.8; font-size: 14px; }}
            .content {{ padding: 20px; }}
            .section {{ margin-bottom: 25px; border-bottom: 1px solid #eee; padding-bottom: 20px; }}
            .section:last-child {{ border-bottom: none; }}
            .section-title {{ font-size: 16px; font-weight: bold; color: #2c3e50; margin-bottom: 15px; text-transform: uppercase; letter-spacing: 0.5px; border-left: 4px solid #3498db; padding-left: 10px; }}
            
            /* Status Badges */
            .badge {{ display: inline-inline; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; color: #fff; }}
            .bg-success {{ background-color: #27ae60; }}
            .bg-danger {{ background-color: #e74c3c; }}
            .bg-warning {{ background-color: #f39c12; }}
            .bg-info {{ background-color: #3498db; }}
            
            /* Stats Grid */
            .stats-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 15px; }}
            .stat-item {{ background: #f8f9fa; padding: 10px; border-radius: 6px; }}
            .stat-label {{ font-size: 12px; color: #7f8c8d; display: block; }}
            .stat-value {{ font-size: 16px; font-weight: bold; color: #2c3e50; }}
            
            /* Progress Bars */
            .progress-container {{ margin-top: 5px; background: #e9ecef; border-radius: 4px; height: 6px; width: 100%; overflow: hidden; }}
            .progress-bar {{ height: 100%; border-radius: 4px; }}
            
            /* Service List */
            .service-list {{ width: 100%; border-collapse: collapse; }}
            .service-list td {{ padding: 10px; border-bottom: 1px solid #f1f1f1; }}
            .service-name {{ font-weight: 500; }}
            .footer {{ background: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #95a5a6; border-top: 1px solid #eee; }}
            .footer a {{ color: #3498db; text-decoration: none; }}
            
            @media only screen and (max-width: 600px) {{
                .container {{ margin: 0; border-radius: 0; }}
                .stats-grid {{ grid-template-columns: 1fr; }}
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>{title}</h1>
                <p>{subtitle}</p>
            </div>
            <div class="content">
                {content}
            </div>
            <div class="footer">
                <p>Generated by <strong>Server Angel</strong> &bull; {hostname}</p>
                <p>&copy; 2025 NHT Corporations Limited</p>
            </div>
        </div>
    </body>
    </html>
    """

    @staticmethod
    def _get_progress_color(percentage):
        """Return color based on usage percentage."""
        try:
            val = float(percentage.strip('%'))
            if val < 60: return "#27ae60"  # Green
            if val < 85: return "#f39c12"  # Orange
            return "#e74c3c" # Red
        except:
            return "#3498db"

    @staticmethod
    def build_health_report(health_data, report_type="daily"):
        """Build health check email report (Text + HTML)."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        hostname = socket.gethostname()
        title = f"Health Report: {report_type.title()}"
        
        # --- Plain Text Generation (Legacy) ---
        subject = f"🛡️ {report_type.title()} Health - {hostname}"
        
        text_body = f"🛡️ SERVER ANGEL - {report_type.upper()} HEALTH REPORT\n{'=' * 50}\n\n"
        text_body += f"Server: {hostname}\nTime: {timestamp}\n\n"
        
        # --- HTML Content Generation ---
        html_content = ""
        
        # 1. System Status
        system = health_data.get('system', {})
        html_content += '<div class="section"><div class="section-title">🖥️ System Status</div><div class="stats-grid">'
        
        metrics = [
            ('CPU Usage', system.get('cpu_usage', '0%')),
            ('Memory', system.get('memory_usage', '0%')),
            ('Disk', system.get('disk_usage', '0%')),
            ('Uptime', system.get('uptime', 'N/A'))
        ]
        
        for label, value in metrics:
            text_body += f"{label}: {value}\n"
            
            # HTML Progress Bar for percentage values
            progress_html = ""
            if '%' in value:
                color = EmailReporter._get_progress_color(value)
                width = value.strip('%')
                progress_html = f'<div class="progress-container"><div class="progress-bar" style="width: {width}%; background-color: {color};"></div></div>'
            
            html_content += f"""
            <div class="stat-item">
                <span class="stat-label">{label}</span>
                <span class="stat-value">{value}</span>
                {progress_html}
            </div>
            """
        html_content += '</div></div>'
        text_body += "\n"

        # 2. Services Status
        text_body += f"🔧 SERVICES STATUS\n{'-' * 20}\n"
        html_content += '<div class="section"><div class="section-title">🔧 Services Status</div><table class="service-list">'
        
        services = health_data.get('services', [])
        running_count = 0
        total_count = 0
        
        for service in services:
            name = service.get('name', 'Unknown')
            status = service.get('status', 'UNKNOWN')
            details = service.get('details', '')
            
            if status == 'NOT_CONFIGURED':
                continue
                
            total_count += 1
            
            # Text Version
            icon = "✅" if status in ['RUNNING', 'OK'] else "❌"
            text_body += f"{icon} {name}: {status}\n"
            
            # HTML Version
            badge_class = "bg-success" if status in ['RUNNING', 'OK'] else "bg-danger"
            if status == 'UNKNOWN': badge_class = "bg-warning"
            
            html_content += f"""
            <tr>
                <td class="service-name">{name}</td>
                <td><span class="badge {badge_class}">{status}</span></td>
            </tr>
            """
            
            if status in ['RUNNING', 'OK']:
                running_count += 1

        html_content += '</table></div>'
        
        # 3. Summary
        text_body += f"\n📊 SUMMARY\n{'-' * 10}\n"
        status_msg = f"All systems operational ({running_count}/{total_count} running)"
        if running_count < total_count:
            status_msg = f"⚠️ Issues detected: {total_count - running_count} services down"
            
        text_body += status_msg + "\n"
        
        summary_color = "#27ae60" if running_count == total_count else "#e74c3c"
        html_content += f"""
        <div class="section" style="text-align: center; color: {summary_color}; font-weight: bold;">
            {status_msg}
        </div>
        """

        # Final HTML Assembly
        full_html = EmailReporter.HTML_TEMPLATE.format(
            title=title,
            subtitle=f"{timestamp} &bull; {hostname}",
            content=html_content,
            hostname=hostname
        )

        return subject, text_body, full_html

    @staticmethod
    def build_deployment_report(deployment_data):
        """Build deployment report (Text + HTML)."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        hostname = socket.gethostname()
        
        success = deployment_data.get('success', False)
        commit = deployment_data.get('commit_hash', 'Unknown')[:8]
        
        status_text = "SUCCESS" if success else "FAILED"
        subject = f"{'🚀' if success else '❌'} Deploy {status_text} - {commit} - {hostname}"
        
        # --- Plain Text ---
        text_body = f"DEPLOYMENT REPORT\nStatus: {status_text}\nCommit: {commit}\n\n"
        
        # --- HTML Content ---
        color = "#27ae60" if success else "#e74c3c"
        html_content = f"""
        <div class="section" style="text-align: center;">
            <div style="font-size: 24px; font-weight: bold; color: {color}; margin-bottom: 10px;">
                DEPLOYMENT {status_text}
            </div>
            <div style="background: #f8f9fa; padding: 10px; border-radius: 4px; font-family: monospace;">
                Commit: {commit}
            </div>
        </div>
        <div class="section"><div class="section-title">📋 Deployment Steps</div><table class="service-list">
        """
        
        steps = deployment_data.get('steps', [])
        for step in steps:
            name = step.get('step', '').replace('_', ' ').title()
            step_status = step.get('status', 'UNKNOWN').upper()
            
            # Text
            text_body += f"{name}: {step_status}\n"
            
            # HTML
            badge_class = "bg-success" if step_status == 'SUCCESS' else "bg-danger"
            html_content += f"""
            <tr>
                <td class="service-name">{name}</td>
                <td><span class="badge {badge_class}">{step_status}</span></td>
            </tr>
            """
            
        html_content += "</table></div>"
        
        if 'error' in deployment_data:
            err = deployment_data['error']
            text_body += f"\nERROR: {err}\n"
            html_content += f"""
            <div class="section">
                <div class="section-title" style="color: #e74c3c;">❌ Error Details</div>
                <div style="background: #fff5f5; color: #c0392b; padding: 10px; border-radius: 4px; font-size: 13px;">
                    {err}
                </div>
            </div>
            """

        full_html = EmailReporter.HTML_TEMPLATE.format(
            title="Deployment Notification",
            subtitle=f"{timestamp} &bull; {commit}",
            content=html_content,
            hostname=hostname
        )
        
        return subject, text_body, full_html

    @staticmethod
    def build_error_report(error_message, context="general"):
        """Build error alert (Text + HTML)."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        hostname = socket.gethostname()
        subject = f"🚨 Error Alert - {context} - {hostname}"
        
        text_body = f"ERROR ALERT\nContext: {context}\n\n{error_message}"
        
        html_content = f"""
        <div class="section">
            <div class="section-title" style="color: #e74c3c;">🚨 Error Alert</div>
            <p><strong>Context:</strong> {context}</p>
            <div style="background: #fff5f5; color: #c0392b; padding: 15px; border-radius: 4px; font-family: monospace; font-size: 13px;">
                {error_message}
            </div>
        </div>
        """
        
        full_html = EmailReporter.HTML_TEMPLATE.format(
            title="System Alert",
            subtitle=f"{timestamp}",
            content=html_content,
            hostname=hostname
        )
        
        return subject, text_body, full_html

